version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestDepProject
  gitServerName: dima
  gitUrl: https://github.com/deemashlayer/TestDepProject
  gitUsername: deemashlayer
  gitBranch: main
